Fix copilot breakage
Yes, this function must not be constexpr, but it's also defined in a header included in multiple translation units, so it must be `inline` to avoid 

> /usr/bin/ld: CMakeFiles/rosx_introspection.dir/src/serializer.cpp.o: in function `nanocdr::getCurrentEndianness()':
./.obj-x86_64-linux-gnu/plotjuggler_plugins/ParserROS/rosx_introspection/./plotjuggler_plugins/ParserROS/rosx_introspection/include/rosx_introspection/contrib/nanocdr.hpp:336: multiple definition of `nanocdr::getCurrentEndianness()'; CMakeFiles/rosx_introspection.dir/src/deserializer.cpp.o:./.obj-x86_64-linux-gnu/plotjuggler_plugins/ParserROS/rosx_introspection/./plotjuggler_plugins/ParserROS/rosx_introspection/include/rosx_introspection/contrib/nanocdr.hpp:336: first defined here
collect2: error: ld returned 1 exit status